Updating so that it works with django's updated command API
thread/django-yadt pull request #2
Opened 2016-11-11 15:02 UTC by vikki

since 1.8 django argument parsing has changed
Also API for requesting models has changed (old way is deprecated)

2016-11-11 15:04 UTC, lamby requested changes

2016-11-11 15:04 UTC, lamby commented on django_yadt/management/commands/yadt_refresh_variant.py
> +        parser.add_argument('app_label', type=str)
is ``type=str`` not the default?

2016-11-11 15:15 UTC, vikki commented on django_yadt/management/commands/yadt_refresh_variant.py
> +        parser.add_argument('app_label', type=str)
Yes, looks like it. Normally I'd prefer that it was more explicit, but I guess it's just noise here so I've taken it out

2016-11-11 15:27 UTC, lamby commented on django_yadt/management/commands/yadt_refresh_variant.py
> +            options['variant_name']
missing tailing comma

2016-11-11 15:40 UTC, lamby commented
:)

2016-11-14 16:06 UTC, tomokas approved these changes
:+1:

2016-11-16 10:34 UTC, merged